### ISSUE TITLE
Missing metadata on Project Detail Page

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1061]
*Taken from #1060:*

There is a few pieces of metadata that we're missing on the project detail pages, which are:

- [x] *Author / Author-Email:* Pretty obvious, and already being covered by #1060.
- [x] *Maintainer / Maintainer-Email:* Also pretty obvious, also likely being covered by #1060.
- [x] ~~*Platform / Supported-Platform:* These are defined as a list of strings that indicate what platform the package is targeting~~
- [x] *License:* This is a string that should be used in cases that there isn't a classifier that indicates what license something is.
- [x] *Classifiers:* A list of strings which are valid classifiers. *Fixed in #1246*
- [x] *Requires-Dist*
- [x] ~~*Provides-Dist*~~
- [x] ~~*Obsoletes-Dist*~~
- [x] ~~*Requires / Provides / Obsoletes:* Similar to the `-Dist` variants, but deprecated and deals with ``import``able things rather than things on PyPI.~~
- [x] *Requires-Python:* What versions of Python this project works on.
- [x] ~~*Requires-External:* What external things are required by this project.~~

Off hand, I'd say we defintely don't want to expose ``Requires``, ``Provides``, and ``Obsoletes``. They are deprecated and they don't generally do things that people expect them to do, I think they just serve to confuse people.

I'd also say that ``Requires-External`` was never actually used and badly scoped, so we shouldn't bother to display it either.

``Platform`` and ``Supported-Platform`` are possibly useful, but I don't think they have widespread use so it may not make sense to bother to display them, I'm not sure.

The ``License`` field is a bit tricky. It's *supposed* to only be used if a classifier doesn't accurately or completely describe your license, however sometimes people include duplicative data in there. In addition sometimes people include the *entire* text of the license there othertimes they just list things like "GPL with a Linking Exception". Off hand, I think maybe a dedicated tab that only shows up if the license field is populated might make sense?

For ``Requires-Dist``, we're going to support that but that's already been designed.

I'm unsure about ``Provides-Dist``, nothing actually pays attention to it and very few things provide that metadata. Theoretically in the future we might use it though (or maybe not, but something like it?).

I don't think we should expose ``Obsoletes-Dist``, it goes in the "wrong" direction (e.g., why does project Foo get the ability to say project Bar is obsoleted?) and nothing actually uses it.

Nothing is using or writing ``Requires-Python``, but I think it's got the potential to be useful and we should do something with it, so I'd say we should add it to the design.

**Comment by nlhkabu** [comment]
I've updated the list above.

Anything that is checked has been 'dealt with' - it is either:

- already in the UI, or
- logged in a separate issue, or 
- is not being exposed.

Anything that is crossed out is not going to be exposed in the UI.

@dstufft - Am I right in understanding that `Requires-Dist` is being covered by the dependencies tab?  The same for `Provides-Dist` with the reverse dependencies? If so, please check the boxes :)

If that's correct, the only remaining item is `requires-python`, which we can expose in the meta data sidebar.

**Comment by dstufft** [comment]
@nlhkabu Yes, ``Requires-Dist`` is covered by Dependencies, ``Provides-Dist`` is not. ``Provides-Dist is not "what depends on me" but "what names/versions do I provide" and everything has an implicit "whatever the project name and release version is". Nothing really uses it at the moment though so it might make sense to hide it until something actually uses it for something meaningful.

Adding ``requires-python`` would be good, probably something that can wait until after launch though because while I think it's a generally useful feature, I don't think anyone currently uses it (because setuptools doesn't expose it).

**Comment by nlhkabu** [comment]
Ok, I've opened a separate specific issue for this - see https://github.com/pypa/warehouse/issues/1324

As all other meta data is either not going to be exposed or is covered by separate issues, I am going to close this issue now.  \o/
