### ISSUE TITLE
Create an Organization account

### ISSUE THREAD

**Issue by s-mm** [pypa/warehouse#11070]
Feature request for organization account project in PyPI.

Description | Users can create a new Organization account. The name of the account will reflect the Organization’s name.
-- | --
User value | The Organization account will allow entities to own Projects on PyPI and assign permission levels across team members and projects
Acceptance criteria | Email notification to PyPI Admin and account creator. Pending Organization visible in the PyPI Admin panel including necessary information for review. Approval and rejection actions in the PyPI Admin to either create the organization or reject it.

**Comment by divbzero** [comment]
### Tasks

- [ ] Database: Create Organization table
- [ ] Database: Create OrganizationRole table
- [ ] Database: Create OrganizationRoleInvitation table
- [ ] Database: Create OrganizationNameCatalog table
- [ ] Database: Create OrganizationProject table
- [ ] Interface: List organizations
- [ ] Interface: Find organization by name
- [ ] Interface: Create new organization request
- [ ] UI: List or create organization
- [ ] UI: Confirm new organization request
- [ ] Email: Create organization requested confirmation for user
- [ ] Email: Create organization requested notification for PSF admin
