### ISSUE TITLE
Reach out to 3rd party services about new pypi.org domain

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2935]
We should reach out to any 3rd party service that depends on the `pypi.python.org` domain and encourage them to update to `pypi.org`.

A list of services that currently depend on `pypi.python.org`:

- [x] https://badge.fury.io/for/py (clicking the badge directs the user to `pypi.python.org`)
- [x] https://pyup.io/ (PRs currently link to `pypi.python.org`)
- [x] [TravisCI](https://docs.travis-ci.com/user/deployment/pypi/) ("can automatically release your Python package to [PyPI](https://pypi.python.org/) after a successful build." May fix travis-ci/dpl#377?)
- [x] [CircleCI](https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/) (similar)
- [x] [sphinx-pypi-upload](https://bitbucket.org/jezdez/sphinx-pypi-upload/)
- [x] [the cheeseshop extension to Sphinx](https://bitbucket.org/birkenfeld/sphinx-contrib/src/8e295053a27d5914127fbb01e2a8fb57421897a7/cheeseshop/?at=default) (["easily link to PyPI packages"](http://www.sphinx-doc.org/en/master/develop.html#extensions))
- [x] [Pydoc.io](https://blog.readthedocs.com/announcing-pydoc-io/) ([site](https://www.pydoc.io/), [code](https://github.com/rtfd/pydoc.io); grabs PyPI packages and builds API docs)
- [x] possibly [PythonAnywhere](https://www.pythonanywhere.com/) which gives people hosted Python environments & links to [projects on legacy PyPI](https://www.pythonanywhere.com/batteries_included/) & may run a mirror? to handle [`pip install`](https://help.pythonanywhere.com/pages/InstallingNewModules)
- [x] the Debian [`watch`](https://wiki.debian.org/debian/watch) folks and [`devscripts` (including `uscan`)](https://manpages.debian.org/stretch/devscripts/uscan.1.en.html) folks, such as Piotr Roszatycki, as they hit legacy PyPI ([`uscan`](https://manpages.debian.org/stretch/devscripts/uscan.1.en.html#PyPI), [`watch`](https://wiki.debian.org/debian/watch#PyPI)) and produce pypi.debian.net ([example](http://pypi.debian.net/arrow)) and [have asked about Warehouse supporting `uscan` more cleanly](https://github.com/pypa/warehouse/issues/358#issuecomment-337233792)
- [x] [Enthought whose Canopy is a curated Python package list](http://docs.enthought.com/python-for-LabVIEW/guide/python.html#installing-python-packages)
- [x] http://shields.io/ (badges)
- [x] Anitya (see https://github.com/release-monitoring/anitya/issues/531 & below)
- [x] libraries.io
- [x] release-monitoring.org

**Comment by brainwane** [comment]
Add:

- [ ] [TravisCI](https://docs.travis-ci.com/user/deployment/pypi/) ("can automatically release your Python package to [PyPI](https://pypi.python.org/) after a successful build.")
- [ ] [CircleCI](https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/) (similar)

**Comment by ncoghlan** [comment]
Open source release tracking services like release-monitoring.org and libraries.io will also be affected.

I filed https://github.com/release-monitoring/anitya/issues/531 for Anitya, and based on an initial review, the info we'll need for that migration is:

* the basic project page relocation (which I already know: `https://pypi.python.org/pypi/{name}` -> `https://pypi.org/project/{name}`)
* the JSON API relocation (that was previously a matter of appending `/json` to the project page reference)
* the new endpoint for the package upload RSS feed

**Comment by dstufft** [comment]
URLs should be the same or redirect to their new location, just with the domain changed.

**Comment by mgedmin** [comment]
http://shields.io/ can do PyPI badges, they might need a heads up.

**Comment by di** [comment]
@brainwane Perhaps we should put together a "Migrating from pypi.python.org to pypi.org" document for 3rd parties that answers the questions @ncoghlan has (and any other), which we can point them to when we "reach out" to them.

**Comment by ncoghlan** [comment]
@di We have https://packaging.python.org/guides/migrating-to-pypi-org/, but it's currently focused on migrations for tool configurations and interactive use.

For the lower level details of API & URL migrations, I suspect a contributor focused document in Warehouse explaining the handling of the paths below `/pypi/` would make sense, and then the packaging.python.org page can add a new short subsection that links to that after explaining that replacing `pypi.python.org` with `pypi.org` is expected to "just work" for any client that correctly follows redirects.

Also providing updated answers for my own questions (based on @dstuft's advice above):

* `https://pypi.org/pypi/fedmsg` (with or without a trailing slash) redirects to `https://pypi.org/project/fedmsg/`
* `https://pypi.org/pypi/fedmsg/json` returns the expected JSON response directly (my mistake was switching out `pypi` for `project` in the URL path)
* `https://pypi.org/pypi?%3Aaction=rss` redirects to `https://pypi.org/rss/updates.xml`

**Comment by ncoghlan** [comment]
Huh, it looks like `pypi.org` honours an `Accept-Encoding: gzip` header, whereas `pypi.python.org` ignored it. That may uncover some latent defects in clients that are setting that header, but not actually handling a gzip encoded response properly (with Anitya and/or Anitya's test suite potentially being one such client).

**Comment by ncoghlan** [comment]
Turns out Anitya could handle the `gzip` encoding support just fine, we just needed to update some of the tests to account for the refreshed recorded responses from PyPI.

**Comment by brainwane** [comment]
> @brainwane Perhaps we should put together a "Migrating from pypi.python.org to pypi.org" document for 3rd parties that answers the questions @ncoghlan has (and any other), which we can point them to when we "reach out" to them.

I agree. Started in #3153.

It would be great to have #3151 for this as well.

**Comment by jayfk** [comment]
pyup.io is notified 👍🏼

**Comment by dstufft** [comment]
> JSON API https://warehouse.readthedocs.io/api-reference/json/

This isn't a new feature, legacy had it and Warehouse just mimic'd it.

**Comment by ncoghlan** [comment]
Regarding GPG signatures: one of the risks that publisher signatures defend against is a compromise of *PyPI itself* (whether that's a technical compromise by a third party, or malicious action by a PyPI admin). However, for them to effectively serve that purpose, signatures need to be obtained through a trusted channel *that isn't PyPI*. As a reference link, https://mail.python.org/pipermail/distutils-sig/2017-March/030252.html would be a reasonable one (both Donald and I have written about the topic at various points over the years, that's just the one that came up first for me in Google)

Regarding PEP 541: the requirements for declaring a package as abandoned are pretty stringent, so we don't expect the number of transfer requests to increase substantially, but we do expect them to be resolved in a more timely fashion when they do come up.

**Comment by brainwane** [comment]
I updated a bit of the comment - thanks for your feedback, Donald and Nick. Now I'll use it to send notes to some of the sites and projects listed above.

**Comment by brainwane** [comment]
badges/shields#1569, librariesio/libraries.io#2024.

**Comment by dstufft** [comment]
As far as GPG and PyPI goes, the delta between legacy and Warehouse is uh:

* Warehouse doesn't expose the fact a file had a signature uploaded for it in the UI.
* Warehouse doesn't have a UI for users to manage their GPG public key.

I don't think anything else has changed, and both of those are UI things so it probably doesn't need called out specifically since a lot of UI stuff changed?

**Comment by brainwane** [comment]
@dstufft when you say "Warehouse doesn't expose the fact a file had a signature uploaded for it in the UI." I see, you mean the web UI, and Ernest was referring to the Simple API. Thanks.

I do think the things you mention do need calling out because - in my experience - while "foo has moved over to another page/a sidebar" doesn't need much explicit guidance, "foo that you used to see/use is now gone" will cause confusion and support requests unless we explicitly forestall that by saying "you haven't missed it, it's actually gone now, deliberately." I'll add a brief note to my boilerplate.

**Comment by dstufft** [comment]
That works. If you want to see the difference you can look at https://pypi.python.org/pypi/pip versus https://pypi.org/project/pip/#files. The former has a (php) link, and the latter does not.

I might be wrong about the managing your GPG key part, I just logged into legacy to get a link for the page and I don't see it anymore. I suspect @ewdurbin or @di removed it from legacy at some point and I didn't notice (or I forgot).

That reminds me of another difference though, Warehouse no longer has a mechanism for managing your SSH key either (and PyPI still has this). The practical difference is minuscule though, because the code that utilized the user's SSH key got ripped out like 4 years ago so managing your SSH key doesn't really do anything except update an otherwise unused field in a database.

**Comment by brainwane** [comment]
mosquito/pypi-server#30, circleci.py#40, an email to CircleCI support, email to gemfury about badges, and email to PythonAnywhere sent.

**Comment by brainwane** [comment]
Emailed Paul Tagliamonte, Barry Warsaw, and Piotr Roszatycki with a heads-up and asked for it to be forwarded to [the `debian-python` list](https://lists.debian.org/debian-python/). Email sent to Jannis Leidel and WoLpH about `sphinx-pypi-upload`. Email sent to Georg Brandl about the Sphinx `cheeseshop` extension. And edited the announcement text from my comment above and put it on the wiki at https://wiki.python.org/psf/PackagingWG/PyPIBetaAnnouncement .

Am calling this complete. We can start a new issue if we start discovering more services to alert.

**Comment by di** [comment]
@jayfk Noticed that pyup is still using pypi.python.org, anything we can do to help?

**Comment by jayfk** [comment]
> @jayfk Noticed that pyup is still using pypi.python.org, anything we can do to help?

I need some kind of cloning device :D. I have the updated URLs in a local branch, just need to re-run tests and merge it in.

Thanks for keeping an eye out for this!

**Comment by pradyunsg** [comment]
We didn't reach out to https://pythonwheels.com, did we?

Project: https://github.com/meshy/pythonwheels

**Comment by di** [comment]
Hey @meshy, are you aware of this? Anything we can do to help?

**Comment by meshy** [comment]
Hey @di and @pradyunsg, thanks for reaching out!

I've been aware of the upcoming changes for a while, thanks to @hugovk. They've been a star, and have done the leg-work for me in terms of migrating the project over to using BigQuery.

I've not had the time to merge the required changes, but I hope that pythonwheels will be ready when the change comes.

Also, amazing job on Warehouse! It's awesome!

**Comment by hugovk** [comment]
You're welcome. See https://hugovk.github.io/top-pypi-packages/ for a weekly dump of the 5,000 most-downloaded packages from PyPI, as a replacement for the old [`top_packages`](https://github.com/pypa/warehouse/pull/2480).
